### ISSUE TITLE
Icarus w/ noverworld

### ISSUE THREAD

**Issue by xTremeBot92** [logwet/noverworld#1]
Change c+9 or 9th saved hotbar to anything with either a blank space or 64 fireworks. Once you boot up a world with the icarus mod and the noverworld mod in your mod folder. You will enter a world with an elytra and 64 fireworks.

**Comment by logwet** [comment]
Thank you for documenting this! This will work until I implement the JSON based inventory config system, coming soon™ in version `1.5.x`

**Comment by logwet** [comment]
Actually I won't close this just for visibility.

**Comment by logwet** [comment]
Noverworld switched from the creative hotbars system to a json file a long time ago but I forgot to update this. All you have to do is edit your local config to leave a slot free, then have your icarus datapack/mod dump your fireworks in that slot.
