### ISSUE TITLE
Noverworld says "Errors in currently selected datapacks prevented world from loading" when trying to create a new world.

### ISSUE THREAD

**Issue by ChickenCroissant** [logwet/noverworld#3]

**Comment by logwet** [comment]
Please attach a crash report or your minecraft log to this issue. Pastebin or a GitHub Gist would be a good way to do it. If you’re posting your minecraft log don’t forget to redact any personal information. I’d also like a list of every mod besides noverworld you’re running and their versions.

**Comment by logwet** [comment]
Closing due to lack of response. Feel free to re-open if you can provide your game logs.
